### ISSUE TITLE
zeligproject.org: zelig-logitgee example broken

### ISSUE THREAD

**Issue by tercer** [IQSS/docs.zeligproject.org#17]
<img width="890" alt="screen shot 2017-04-12 at 6 52 32 pm" src="https://cloud.githubusercontent.com/assets/2085037/24982810/6cd6c330-1fb1-11e7-92a2-8ea69c58a18e.png">

**Comment by christophergandrud** [comment]
Loaded missing geepack package in 0ddaac087f3715a56fca625682c2d54cd5470c5d

**Comment by tercer** [comment]
Right.  That is fine.  If I'd looked at the error more closely would have done this right away.
