### ISSUE TITLE
zeligproject: 25 examples broken from the sim command

### ISSUE THREAD

**Issue by tercer** [IQSS/docs.zeligproject.org#18]
Every model from ``mlogitbayes`` onwards is broken at the ``sim()`` command.  The examples seem to work in local mode, so it is a problem with the build process for the docs.  Here are some examples:

<img width="870" alt="screen shot 2017-04-13 at 2 40 16 pm" src="https://cloud.githubusercontent.com/assets/2085037/25019775/d328714e-2059-11e7-8388-10d002d8bd77.png">
<img width="875" alt="screen shot 2017-04-13 at 2 40 36 pm" src="https://cloud.githubusercontent.com/assets/2085037/25019783/d68c0288-2059-11e7-920a-79e8089f3090.png">

Since this is a break at the point of ``sim()`` it suggests it is related to #16 which breaks at this point also, although with a different error message.

**Comment by cchoirat** [comment]
Could it be because of missing packages on the VM (e.g., `Formula`)?
https://github.com/IQSS/zeligproject.org/blob/master/deploy/librarysetup.r#L1-L29

**Comment by tercer** [comment]
Good idea.  I added `Formula` which did not fix things, but will look for more missing packages.

**Comment by tercer** [comment]
Clearly necessary (also added `Matchit` and `coda` ), but didn't suffice to fix anything.

**Comment by christophergandrud** [comment]
Should be resolved by b2e1582b4f93c8984e287d6174434b3e1fe7746b

Problem appears to be an import conflict in ZeligMultilevel with `sim` from the arm package.

See: https://github.com/IQSS/Zelig/issues/252
